version: "3.9"
services:
  app:
    build: .
    image: nodenotes
    restart: always
    environment:
      - APP_PORT=8080
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5431
      - DATABASE_NAME=NodeNotes
      - DATABASE_PASSWORD=postgres

      - JWT_SECRET=fdkslhfdshgjldsngklds
      - JWT_EXPIRATION=24h
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - nodenotes
  
  postgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - '5431:5431'
    volumes: 
      - postgres:/var/lib/postgresql/data

networks:
  nodenotes:
    name: nodenotes
    driver: bridge

volumes:
  postgres:
    driver: local